version: "3"

services:
  chatservice:
    build: .
    container_name: chatservice_app
    volumes:
      - .:/go/src
    ports:
      - "8080:8080"
      - "50052:50051"

  mysql_fclx:
    image: mysql
    container_name: mysql_fclx
    environment:
      - MYSQL_ROOT_PASSWORD=123@mudar
      - MYSQL_DATABASE=chat_test
      - MYSQL_PASSWORD=123@mudar
    ports:
      - "63306:3306"
    volumes:
      - .docker/mysql:/var/lib/mysql