version: "3"

services:
  appnext:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  db_next:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chat
    ports:
      - 53306:3306
    volumes:
     - .docker/dbdata:/var/lib/mysql

  keycloak_next:
    image: quay.io/keycloak/keycloak:21.0
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin